import express from 'express';
import cors from 'cors';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import si from 'systeminformation';

const execAsync = promisify(exec);
const app = express();
const PORT = 3001;

app.use(cors());
app.use(express.json());

// API route to list block devices (disks)
app.get('/api/disks', async (req, res) => {
    try {
        const { stdout } = await execAsync('lsblk -J -o NAME,SIZE,TYPE,MOUNTPOINTS,FSTYPE,MODEL,SERIAL');
        const data = JSON.parse(stdout);
        const blockDevices = data.blockdevices.filter(dev => dev.type === 'disk' && !dev.name.startsWith('loop'));
        
        // Fallback since si.smart is not working
        const smartData = [];
        
        const enhancedDisks = blockDevices.map(disk => {
            return {
                ...disk,
                temperature: 'Unknown',
                health: 'Unknown'
            };
        });

        res.json({ success: true, disks: enhancedDisks });
    } catch (error) {
        console.error('Error fetching disks:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// API route to get MergerFS pool size
app.get('/api/system/storage', async (req, res) => {
    try {
        const fsSize = await si.fsSize();
        const pool = fsSize.find(f => f.mount === '/mnt/pool');
        if (pool) {
            res.json({ success: true, total: pool.size, used: pool.used, use: pool.use });
        } else {
            res.json({ success: true, total: 0, used: 0, use: 0, message: "Pool not mounted" });
        }
    } catch (error) {
        console.error('Error fetching storage:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// API route to get live system metrics
app.get('/api/system/stats', async (req, res) => {
    try {
        const [cpu, mem, net] = await Promise.all([
            si.currentLoad(),
            si.mem(),
            si.networkStats()
        ]);
        
        // Get the active interface (usually the first one with traffic)
        const activeNet = net.find(n => n.rx_bytes > 0 || n.tx_bytes > 0) || net[0];

        res.json({ 
            success: true, 
            cpu: cpu.currentLoad,
            memory: { total: mem.total, used: mem.active, percent: (mem.active / mem.total) * 100 },
            network: { rx_sec: activeNet?.rx_sec || 0, tx_sec: activeNet?.tx_sec || 0 }
        });
    } catch (error) {
        console.error('Error fetching stats:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// Helper function to dynamically generate snapraid.conf
async function generateSnapraidConfig() {
    try {
        const { stdout: mounts } = await execAsync('ls -1 /mnt');
        const mntDirs = mounts.split('\n').filter(Boolean);
        
        const dataDisks = mntDirs.filter(d => d.startsWith('disk_'));
        const parityDisks = mntDirs.filter(d => d.startsWith('parity_'));

        let config = `
# SnapRAID Configuration
# Automatically generated by SimpleNAS

# Parity drives
`;
        parityDisks.forEach((p, i) => {
            config += `parity /mnt/${p}/snapraid.parity\n`;
        });

        config += `\n# Content files (copies of the index)\n`;
        config += `content /var/snapraid.content\n`;
        dataDisks.forEach((d) => {
            config += `content /mnt/${d}/snapraid.content\n`;
        });

        config += `\n# Data disks\n`;
        dataDisks.forEach((d, i) => {
            config += `disk d${i + 1} /mnt/${d}\n`;
        });

        config += `\n# Excludes\n`;
        config += `exclude *.unrecoverable\nexclude /tmp/\nexclude /lost+found/\n`;

        await fs.writeFile('/etc/snapraid.conf', config, 'utf8');
        console.log('Successfully generated /etc/snapraid.conf');
    } catch (err) {
        console.error('Failed to generate snapraid config:', err);
    }
}

// API route to format a disk and add to pool
app.post('/api/disks/format', async (req, res) => {
    const { disk } = req.body; // e.g., 'sdb'
    
    if (!disk || typeof disk !== 'string' || !disk.match(/^[a-z0-9]+$/)) {
        return res.status(400).json({ success: false, error: 'Invalid disk name' });
    }

    const devicePath = `/dev/${disk}`;
    const partitionPath = `/dev/${disk}1`;

    try {
        // Safety check: Ensure it's not the OS drive by checking if it has a root mountpoint
        const { stdout: lsblkOut } = await execAsync(`lsblk -J -o NAME,MOUNTPOINTS ${devicePath}`);
        const data = JSON.parse(lsblkOut);
        const targetDisk = data.blockdevices[0];
        
        const isOS = targetDisk.children?.some(part => part.mountpoints?.includes('/'));
        if (isOS) {
            return res.status(403).json({ success: false, error: 'Cannot format the OS drive!' });
        }

        // Safety check: check if it's already mounted anywhere
        const isMounted = targetDisk.children?.some(part => part.mountpoints?.length > 0 && part.mountpoints[0] !== null);
        if (isMounted) {
            return res.status(403).json({ success: false, error: 'Disk has mounted partitions. Unmount first.' });
        }

        console.log(`Starting format of ${devicePath}...`);
        
        // 1. Create GPT label
        await execAsync(`parted -s ${devicePath} mklabel gpt`);
        
        // 2. Create primary partition using 100% of space
        await execAsync(`parted -s ${devicePath} mkpart primary ext4 0% 100%`);
        
        // Wait a second for the OS to register the new partition node (/dev/sdb1)
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        // 3. Format to ext4 (-F forces format, -L sets label, -E nodiscard makes it faster on VMs)
        await execAsync(`mkfs.ext4 -F -L data_${disk} ${partitionPath}`);
        
        // 4. Get UUID
        const { stdout: uuidOut } = await execAsync(`blkid -s UUID -o value ${partitionPath}`);
        const uuid = uuidOut.trim();

        // 5. Create mount point
        const mountPoint = `/mnt/disk_${disk}`;
        await execAsync(`mkdir -p ${mountPoint}`);

        // 6. Add to /etc/fstab if not present
        const fstabEntry = `UUID=${uuid} ${mountPoint} ext4 defaults 0 2`;
        await execAsync(`grep -q "${mountPoint}" /etc/fstab || echo "${fstabEntry}" >> /etc/fstab`);

        // 7. Mount the drive
        await execAsync(`mount ${mountPoint}`);

        // 8. Ensure MergerFS pool is in fstab
        const mergerFsEntry = `/mnt/disk_* /mnt/pool fuse.mergerfs defaults,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs 0 0`;
        await execAsync(`mkdir -p /mnt/pool`);
        await execAsync(`grep -q "/mnt/pool" /etc/fstab || echo "${mergerFsEntry}" >> /etc/fstab`);

        // 9. Mount or Remount the pool to include the new drive
        try {
            await execAsync(`mountpoint -q /mnt/pool && umount /mnt/pool`);
        } catch (e) { /* ignore if not mounted */ }
        await execAsync(`mount /mnt/pool`);
        
        await generateSnapraidConfig();
        
        console.log(`Successfully formatted and added ${devicePath} to pool!`);
        res.json({ success: true, message: `Successfully added ${disk} to the storage pool!` });
        
    } catch (error) {
        console.error(`Error formatting ${disk}:`, error);
        res.status(500).json({ success: false, error: error.message || 'Formatting failed' });
    }
});

// API route to format a disk as a Parity drive
app.post('/api/disks/parity', async (req, res) => {
    const { disk } = req.body;
    
    if (!disk || typeof disk !== 'string' || !disk.match(/^[a-z0-9]+$/)) {
        return res.status(400).json({ success: false, error: 'Invalid disk name' });
    }

    const devicePath = `/dev/${disk}`;
    const partitionPath = `/dev/${disk}1`;

    try {
        const { stdout: lsblkOut } = await execAsync(`lsblk -J -o NAME,MOUNTPOINTS ${devicePath}`);
        const data = JSON.parse(lsblkOut);
        const targetDisk = data.blockdevices[0];
        
        const isOS = targetDisk.children?.some(part => part.mountpoints?.includes('/'));
        if (isOS) return res.status(403).json({ success: false, error: 'Cannot use the OS drive!' });

        const isMounted = targetDisk.children?.some(part => part.mountpoints?.length > 0 && part.mountpoints[0] !== null);
        if (isMounted) return res.status(403).json({ success: false, error: 'Disk is mounted. Unmount first.' });

        console.log(`Configuring parity on ${devicePath}...`);
        
        await execAsync(`parted -s ${devicePath} mklabel gpt`);
        await execAsync(`parted -s ${devicePath} mkpart primary ext4 0% 100%`);
        await new Promise(resolve => setTimeout(resolve, 1000));
        await execAsync(`mkfs.ext4 -F -L parity_${disk} ${partitionPath}`);
        
        const { stdout: uuidOut } = await execAsync(`blkid -s UUID -o value ${partitionPath}`);
        const uuid = uuidOut.trim();

        const mountPoint = `/mnt/parity_${disk}`;
        await execAsync(`mkdir -p ${mountPoint}`);

        const fstabEntry = `UUID=${uuid} ${mountPoint} ext4 defaults 0 2`;
        await execAsync(`grep -q "${mountPoint}" /etc/fstab || echo "${fstabEntry}" >> /etc/fstab`);
        await execAsync(`mount ${mountPoint}`);

        await generateSnapraidConfig();
        
        console.log(`Successfully set up ${devicePath} as Parity!`);
        res.json({ success: true, message: `Successfully set ${disk} as Parity drive!` });
        
    } catch (error) {
        console.error(`Error setting parity ${disk}:`, error);
        res.status(500).json({ success: false, error: error.message || 'Parity setup failed' });
    }
});

// API route to get Samba shares
app.get('/api/shares', async (req, res) => {
    try {
        const { stdout: conf } = await execAsync('cat /etc/samba/smb.conf');
        const shares = [];
        const lines = conf.split('\n');
        let currentShare = null;
        
        for (const line of lines) {
            const match = line.match(/^\[(.*)\]$/);
            if (match && match[1] !== 'global') {
                if (currentShare) shares.push(currentShare);
                currentShare = { name: match[1], enabled: true };
            } else if (currentShare && line.trim().startsWith('path =')) {
                currentShare.path = line.split('=')[1].trim();
            }
        }
        if (currentShare) shares.push(currentShare);

        res.json({ success: true, shares });
    } catch (error) {
        console.error('Error fetching shares:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// API route to enable/create default pool share
app.post('/api/shares/enable', async (req, res) => {
    try {
        const shareConfig = `
[SimpleNAS_Pool]
   path = /mnt/pool
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
`;
        await execAsync(`grep -q "\\[SimpleNAS_Pool\\]" /etc/samba/smb.conf || echo "${shareConfig}" >> /etc/samba/smb.conf`);
        await execAsync(`systemctl restart smbd`);
        
        res.json({ success: true, message: 'Share SimpleNAS_Pool enabled successfully!' });
    } catch (error) {
        console.error('Error enabling share:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// API route to set Samba credentials
app.post('/api/shares/credentials', async (req, res) => {
    const { password } = req.body;
    if (!password || password.length < 4) {
        return res.status(400).json({ success: false, error: 'Password must be at least 4 characters' });
    }

    try {
        // Create linux user 'simplenas' if it doesn't exist
        await execAsync(`id -u simplenas || useradd -M -s /usr/sbin/nologin simplenas`);
        
        // Set samba password non-interactively
        await execAsync(`(echo "${password}"; echo "${password}") | smbpasswd -s -a simplenas`);
        
        // Update smb.conf to require the user
        const shareConfig = `
[SimpleNAS_Pool]
   path = /mnt/pool
   browseable = yes
   read only = no
   valid users = simplenas
   force user = root
   create mask = 0777
   directory mask = 0777
`;
        // Remove existing [SimpleNAS_Pool] section and append the secure one
        await execAsync(`sed -i '/\\[SimpleNAS_Pool\\]/,$d' /etc/samba/smb.conf`);
        await execAsync(`echo "${shareConfig}" >> /etc/samba/smb.conf`);
        await execAsync(`systemctl restart smbd`);
        
        res.json({ success: true, message: 'Security updated! Username is: simplenas' });
    } catch (error) {
        console.error('Error setting credentials:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// Basic health check
app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', uptime: process.uptime() });
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`SimpleNAS Backend API listening on port ${PORT}`);
});
